# Generated by Django 4.2 on 2024-12-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberWordsDay', models.IntegerField(verbose_name='количество слов в день')),
                ('amountInputText', models.ImageField(upload_to='', verbose_name='количество ввода текста')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=200)),
                ('ru', models.CharField(max_length=200)),
                ('repetitions', models.IntegerField(verbose_name='количество повторов')),
                ('geeks_field', models.BooleanField(verbose_name='знаю или нет')),
            ],
        ),
        migrations.CreateModel(
            name='WordsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=200)),
                ('ru', models.CharField(max_length=200)),
            ],
        ),
    ]
