# Определяем версию формата Docker Compose
version: '3'

# Определяем сервисы, которые будут запущены
services:
  # Сервис для API
  backend:
    # Указываем путь к Dockerfile для сборки образа
    build: ./backend

    # Определяем порты, которые будут проброшены с хоста на контейнер
    ports:
      - "8000:8000"  # Пробрасываем порт 8000 хоста на порт 8000 контейнера

    # Определяем тома (volumes), которые будут смонтированы в контейнер
    volumes:
      - ./backend/config:/backend  # Монтируем директорию ./api на хосте в директорию /backend в контейнере

    # Указываем команду для запуска приложения в контейнере
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  # Сервис для веб-интерфейса
  web:
    # Указываем путь к Dockerfile для сборки образа
    build: ./frontend

    # Определяем порты, которые будут проброшены с хоста на контейнер
    ports:
      - "3000:3000"  # Пробрасываем порт 3000 хоста на порт 3000 контейнера

    # Определяем тома (volumes), которые будут смонтированы в контейнер
    volumes:
      - ./frontend:/frontend  # Монтируем директорию ./frontend на хосте в директорию /frontend в контейнере
