# Generated by Django 4.2 on 2025-01-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.JSONField()),
                ('week', models.JSONField()),
                ('month', models.JSONField()),
                ('year', models.JSONField()),
                ('All', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberWordsDay', models.IntegerField(default=20, verbose_name='количество за день')),
                ('amountInputText', models.IntegerField(default=10, verbose_name='количество ввода текста')),
                ('numberOptionsGuessing', models.IntegerField(default=8, verbose_name='количесво вариантов при угадывании')),
                ('voiceoverWords', models.BooleanField(default=True, verbose_name='озвучка')),
                ('voiceSpead', models.BooleanField(default=False, verbose_name='скорость озвучки')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=200)),
                ('ru', models.CharField(max_length=200)),
                ('repetitions', models.IntegerField(verbose_name='количество повторов')),
                ('geeks_field', models.BooleanField(verbose_name='знаю или нет')),
                ('timeCreate', models.DateTimeField(auto_now_add=True)),
                ('timeUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=200)),
                ('ru', models.CharField(max_length=200)),
                ('timeCreate', models.DateTimeField(auto_now_add=True)),
                ('timeUpdate', models.DateTimeField(auto_now=True)),
                ('audio', models.FileField(upload_to='audio/')),
                ('audioSlow', models.FileField(upload_to='audio/')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories')),
            ],
        ),
    ]
