# Generated by Django 4.2 on 2024-12-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberWordsDay', models.IntegerField(verbose_name='количество за день')),
                ('amountInputText', models.IntegerField(verbose_name='количество ввода текста')),
                ('numberOptionsGuessing', models.IntegerField(verbose_name='количесво вариантов при угадывании')),
                ('voiceoverWords', models.BooleanField(verbose_name='озвучка')),
                ('transcriptions', models.BooleanField(verbose_name='транскрипция')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=200)),
                ('ru', models.CharField(max_length=200)),
                ('repetitions', models.IntegerField(verbose_name='количество повторов')),
                ('geeks_field', models.BooleanField(verbose_name='знаю или нет')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=200)),
                ('ru', models.CharField(max_length=200)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories')),
            ],
        ),
    ]
